smoketest:
  outputs:
    dev:
      account: MTQUBQE-XK84015 # -> Snowflake UI bottom left : View Account details
      database: store_dev # -> Snowflake UI bottom left : Databases
      password: <Zero Gravitas>
      role: bvd_rw_role # -> Snowflake UI : Switch Role : NIVEAU DE PERMSISISO)SN
      schema: <A Fine Disregard For Awkward Facts>
      threads: 1
      type: snowflake
      user: <Ethics gradient>
      warehouse: WH_XSMALL # -> Snowflake UI -> top right  Warehouses
    dev_sso:
      account: MTQUBQE-XK84015 # -> Snowflake UI bottom left : View Account details
      authenticator: externalbrowser
      database: store_dev # -> Snowflake UI bottom left : Databases
      role: bvd_rw_role # -> Snowflake UI : Switch Role : NIVEAU DE PERMSISISO)SN
      schema: <Grant exchange of views>
      threads: 1
      type: snowflake
      user: <Functional but not ethical>
      warehouse: WH_XSMALL # -> Snowflake UI -> top right  Warehouses
  target: dev
