blank_issues_enabled: false
contact_links:
  - name: "Documentation Store Snowflake"
    url: "https://docs.dashboards-store-snowflake.sciance.ca"
    about: "Consulter la documentation avant d'ouvrir un ticket."
