name: Publier une version GitHub

on:
  push:
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-release
  cancel-in-progress: true

jobs:
  release:
    name: Créer la version
    runs-on: ubuntu-latest
    concurrency: release
    permissions:
      id-token: write
      contents: write

    steps:
      - name: Récupérer le dépôt
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.CICD_PAT_TOKEN || github.token }}

      - name: Calculer la date de publication
        id: date
        run: |
          today_date=$(date +'%Y%m%d')
          echo "today_date=$today_date" >> "$GITHUB_OUTPUT"

      - name: Taguer et publier la version sémantique
        uses: python-semantic-release/python-semantic-release@master
        with:
          github_token: ${{ secrets.CICD_PAT_TOKEN || github.token }}
          args: publish
          build_metadata: ${{ steps.date.outputs.today_date }}
